package com.mock.skybus.b2b.models.orm;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated Jun 4, 2015 4:17:55 PM by Hibernate Tools 4.3.1

/**
 * Address generated by hbm2java
 */
@XmlRootElement
public class Address implements java.io.Serializable {

	private Integer id;
	private User user;
	private String street;
	private String city;
	private String state;
	private String zip;

	public Address() {
	}

	public Address(User user) {
		this.user = user;
	}

	public Address(User user, String street, String city, String state,
			String zip) {
		this.user = user;
		this.street = street;
		this.city = city;
		this.state = state;
		this.zip = zip;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

}
