package com.mock.skybus.b2b.models.orm;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated Jun 6, 2015 6:24:08 PM by Hibernate Tools 4.3.1

/**
 * Book generated by hbm2java
 */
@XmlRootElement
public class Book implements java.io.Serializable {

	private Integer id;
	private Flight flight;
	private User user;
	private int seat;
	private boolean booked;
	private boolean canceled;
	private int trip;

	public Book() {
	}

	public Book(Flight flight, User user, int seat, boolean booked,
			boolean canceled, int trip) {
		this.flight = flight;
		this.user = user;
		this.seat = seat;
		this.booked = booked;
		this.canceled = canceled;
		this.trip = trip;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Flight getFlight() {
		return this.flight;
	}

	public void setFlight(Flight flight) {
		this.flight = flight;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getSeat() {
		return this.seat;
	}

	public void setSeat(int seat) {
		this.seat = seat;
	}

	public boolean isBooked() {
		return this.booked;
	}

	public void setBooked(boolean booked) {
		this.booked = booked;
	}

	public boolean isCanceled() {
		return this.canceled;
	}

	public void setCanceled(boolean canceled) {
		this.canceled = canceled;
	}

	public int getTrip() {
		return this.trip;
	}

	public void setTrip(int trip) {
		this.trip = trip;
	}

}
