package com.mock.skybus.b2b.models.orm;

// Generated Jun 6, 2015 6:28:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Flight generated by hbm2java
 */
@XmlRootElement
public class Flight implements java.io.Serializable {

	private int id;
	private Location locationByOrigin;
	private Location locationByDestination;
	private int eta;
	private int departure;
	private boolean postponed;
	private boolean arrived;
	private int seats;
	private Set books = new HashSet(0);

	public Flight() {
	}

	public Flight(int id, Location locationByOrigin,
			Location locationByDestination, int eta, int departure,
			boolean postponed, boolean arrived, int seats) {
		this.id = id;
		this.locationByOrigin = locationByOrigin;
		this.locationByDestination = locationByDestination;
		this.eta = eta;
		this.departure = departure;
		this.postponed = postponed;
		this.arrived = arrived;
		this.seats = seats;
	}

	public Flight(int id, Location locationByOrigin,
			Location locationByDestination, int eta, int departure,
			boolean postponed, boolean arrived, int seats, Set books) {
		this.id = id;
		this.locationByOrigin = locationByOrigin;
		this.locationByDestination = locationByDestination;
		this.eta = eta;
		this.departure = departure;
		this.postponed = postponed;
		this.arrived = arrived;
		this.seats = seats;
		this.books = books;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Location getLocationByOrigin() {
		return this.locationByOrigin;
	}

	public void setLocationByOrigin(Location locationByOrigin) {
		this.locationByOrigin = locationByOrigin;
	}

	public Location getLocationByDestination() {
		return this.locationByDestination;
	}

	public void setLocationByDestination(Location locationByDestination) {
		this.locationByDestination = locationByDestination;
	}

	public int getEta() {
		return this.eta;
	}

	public void setEta(int eta) {
		this.eta = eta;
	}

	public int getDeparture() {
		return this.departure;
	}

	public void setDeparture(int departure) {
		this.departure = departure;
	}

	public boolean isPostponed() {
		return this.postponed;
	}

	public void setPostponed(boolean postponed) {
		this.postponed = postponed;
	}

	public boolean isArrived() {
		return this.arrived;
	}

	public void setArrived(boolean arrived) {
		this.arrived = arrived;
	}

	public int getSeats() {
		return this.seats;
	}

	public void setSeats(int seats) {
		this.seats = seats;
	}

	@XmlTransient
	public Set getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

}
