package com.mock.skybus.b2b.models.orm;

// Generated Jun 4, 2015 4:17:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Location generated by hbm2java
 */
@XmlRootElement
public class Location implements java.io.Serializable {

	private int id;
	private String state;
	private String city;
	private Set flightsForOrigin = new HashSet(0);
	private Set flightsForDestination = new HashSet(0);

	public Location() {
	}

	public Location(int id, String state, String city) {
		this.id = id;
		this.state = state;
		this.city = city;
	}

	public Location(int id, String state, String city, Set flightsForOrigin,
			Set flightsForDestination) {
		this.id = id;
		this.state = state;
		this.city = city;
		this.flightsForOrigin = flightsForOrigin;
		this.flightsForDestination = flightsForDestination;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@XmlTransient
	public Set getFlightsForOrigin() {
		return this.flightsForOrigin;
	}

	public void setFlightsForOrigin(Set flightsForOrigin) {
		this.flightsForOrigin = flightsForOrigin;
	}

	@XmlTransient
	public Set getFlightsForDestination() {
		return this.flightsForDestination;
	}

	public void setFlightsForDestination(Set flightsForDestination) {
		this.flightsForDestination = flightsForDestination;
	}

}
