package com.mock.skybus.b2b.models.orm;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated Jun 4, 2015 4:17:55 PM by Hibernate Tools 4.3.1

/**
 * Person generated by hbm2java
 */
@XmlRootElement
public class Person implements java.io.Serializable {

	private Integer id;
	private User user;
	private String firstName;
	private String lastName;

	public Person() {
	}

	public Person(User user) {
		this.user = user;
	}

	public Person(User user, String firstName, String lastName) {
		this.user = user;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}
